(module
    (type (func (param i32) (result i32)))
    (type (func (param f32)))
    (type (func))
    (import "foo" "bar" (func (type 1)))
    (func (type 2))
    (func (type 1) (i32.const 42) (drop))
    (table 0 1 funcref)
    (memory 1 1)
    (export "e" (func 1))
    (start 1)
    (data 0 (offset (i32.const 0)) "hi"))
